enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Global Settings

#patches-source = "inotia00/revanced-patches"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"

patches-version = "dev"
cli-version = "dev"

# App Specific Settings

[YouTube-Extended]
app-name = "YouTube"
enabled = true
rv-brand = "ReVanced Extended"
build-mode = "module"
excluded-patches = "'Theme' 'Enable debug logging' 'Swipe controls'"
included-patches = "'MaterialYou'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_red -e 'Overlay buttons' -OiconType=bold"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
version = "20.21.37"

[Music-Extended]
app-name = "Music"
enabled = true
rv-brand = "ReVanced Extended"
build-mode = "module"
excluded-patches = "'Bitrate default value' 'Enable debug logging'"
#included-patches = ""
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=revancify_red -e 'Dark theme' -OmaterialYou=true"
patches-source = "inotia00/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
version = "8.30.54"
arch = "arm64-v8a"

# END
