enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Global Settings

#patches-source = "inotia00/revanced-patches"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"

patches-version = "dev"
cli-version = "dev"

# App Specific Settings

[YouTube-Extended]
app-name = "YouTube"
enabled = true
rv-brand = "ReVanced Extended"
build-mode = "both"
excluded-patches = "'Theme' 'Enable debug logging' 'Alternative thumbnails' 'Swipe controls'"
included-patches = "'MaterialYou' 'Return YouTube Username'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=revancify_red -e 'Overlay buttons' -OiconType=bold"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
version = "auto"

[Music-Extended]
app-name = "Music"
enabled = true
rv-brand = "ReVanced Extended"
build-mode = "both"
excluded-patches = "'Bitrate default value' 'Dark theme' 'Enable debug logging' 'Hide overlay filter' 'Hide player overlay filter'"
included-patches = "'Custom branding icon for YouTube Music'"
patcher-args = "-OappIcon=revancify_red"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
version = "auto"
arch = "both"

# END
